# Extraer los datos desde el CSV

In [1]:
#Ejercicio01: Establecer librerias a utilizar
import pandas as pd

In [5]:
#Ejercicio02: Definir las cabeceras del Dataset
headers = [
    'symboling',
    'normalized-losses',
    'make',
    'aspiration',
    'num-of-doors',
    'body-style',
    'drive-wheels',
    'engine-location',
    'wheel-base',
    'length',
    'width',
    'height',
    'curb-weight',
    'engine-type',
    'num-of-cylinders',
    'engine-size',
    'fuel-system',
    'bore',
    'stroke',
    'compression-ratio',
    'horsepower',
    'horsepower-binned',
    'peak-rpm',
    'city-mpg',
    'highway-mpg',
    'price',
    'city-L/100km',
    'diesel',
    'gas'
]

df = pd.read_csv('autos(in).csv', names= headers, sep=',')

In [20]:
len(headers)

29

In [6]:
df.head()

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,horsepower,horsepower-binned,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,diesel,gas
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,2.68,9.0,111,5000,21,27,13495,NaN,NaN,NaN
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,2.68,9.0,111,5000,21,27,16500,NaN,NaN,NaN
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,3.47,9.0,154,5000,19,26,16500,NaN,NaN,NaN
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,3.4,10.0,102,5500,24,30,13950,NaN,NaN,NaN
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,3.4,8.0,115,5500,18,22,17450,NaN,NaN,NaN

## 1. Validación de los Datos

### Descripción de las variables

- 'symboling' : Nivel de riesgo del seguro , de menor riesgo (-3) a mayor riesgto (3)
- "normalized-losses" : Es la perdida del pago promedio del seguro del auto por año y representa la perdida por año del auto. El valor oscila entre 65 a 256
- 'make' : Marca
- "aspiration" : Como el motor de combustión interno trabaja , puede ser estandar (std) o turbo 
- 'num-of-doors' : Número de puertas
- "body-style" : Carroceria
- 'drive-wheels' : Tracción de las ruedas
- 'engine-location' : Localización del motor
- 'wheel-base' : Distancia entre ejes 
- 'length' : Longitud
- 'width' : Ancho
- 'height': Alto
- 'curb-weight' : Peso del auto con equipación completa
- 'engine-type': Tipo de motor
- 'num-of-cylinders' : Número de cilindros
- 'engine-size' : Tamaño del motor
- 'fuel-system' : Sistema de combustible
- 'bore' : Diámetro
- 'stroke' : Distancia recorrida por el pistón durante cada ciclo
- 'compression-ratio': Ratio de comprensión
- 'horsepower' : Caballos de potencia
- 'horsepower-binned' : Caballos de potencia convertidos en una variable categórica 
- 'peak-rpm' : RPM pico 
- 'city-mpg' : consumo en la ciudad en millas por galon
- 'highway-mpg' : consumo en autopista en millas por galon
- 'price' : Precio
- 'city-L/100km' :  consumo en la ciudad en litros por kilometro
- 'diesel' : variable dummy para consumo por petróleo
- 'gas': variable dummy para consumo por gasoina

In [3]:
#Ejercicio 01: Contar los datos del DataFrame

In [4]:
#Ejercicio 02: Mostrar los 5 primeros datos

In [8]:
#Ejercicio 03: Mostrar los 5 últimos datos
df.tail()

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,horsepower,horsepower-binned,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,diesel,gas
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,3.15,9.5,114,5400,23,28,16845,NaN,NaN,NaN
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,3.15,8.7,160,5300,19,25,19045,NaN,NaN,NaN
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,2.87,8.8,134,5500,18,23,21485,NaN,NaN,NaN
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,3.4,23.0,106,4800,26,27,22470,NaN,NaN,NaN
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,3.15,9.5,114,5400,19,25,22625,NaN,NaN,NaN

In [6]:
#Ejercicio 04: Ordenar los datos por columna

In [9]:
# Ejercicio05: Definir el formato de los datos perdidos
dato_perdido = '?'
nro_price_validate = df['price'].loc[df['price']] != dato_perdido.count()
nro_price_validate

KeyError: "None of [Index(['13495', '16500', '16500', '13950', '17450', '15250', '17710', '18920',\n       '23875', '?',\n       ...\n       '13415', '15985', '16515', '18420', '18950', '16845', '19045', '21485',\n       '22470', '22625'],\n      dtype='object', length=205)] are in the [index]"

In [7]:
# Ejercicio06: Definir valor perdido de Numpy
import numpy as np
type(np.nan)

float

In [8]:
# Ejercicio07: Reemplazar los valores perdidos por el valor de Numpy
df_replaced = df.replace("?", np.nan, inplace=False)
df_replaced.head()

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,horsepower,horsepower-binned,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,diesel,gas
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,2.68,9.0,111,5000,21,27,13495,NaN,NaN,NaN
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,2.68,9.0,111,5000,21,27,16500,NaN,NaN,NaN
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,3.47,9.0,154,5000,19,26,16500,NaN,NaN,NaN
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,3.4,10.0,102,5500,24,30,13950,NaN,NaN,NaN
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,3.4,8.0,115,5500,18,22,17450,NaN,NaN,NaN

In [9]:
# Ejercicio08: Reemplazar los valores NaN por la media para el precio
avg_price = df_replaced['price'].astype('float').mean()
avg_price
df_replaced['price'].replace(np.nan, avg_price, inplace=True)

C:\Users\Usuario\AppData\Local\Temp\ipykernel_4536\622744921.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_replaced['price'].replace(np.nan, avg_price, inplace=True)

In [10]:
#Ejercicio09: Ordenar los datos por columna de forma descendente
df_replaced.sort_values('make', ascending=False)

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,horsepower,horsepower-binned,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,diesel,gas
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,3.15,9.5,114,5400,19,25,22625,NaN,NaN,NaN
199,-1,74,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,3.15,7.5,162,5100,17,22,18950,NaN,NaN,NaN
194,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,3.15,9.5,114,5400,23,28,12940,NaN,NaN,NaN
195,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,3.15,9.5,114,5400,23,28,13415,NaN,NaN,NaN
196,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,3.15,9.5,114,5400,24,28,15985,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,3.4,8.0,115,5500,18,22,17450,NaN,NaN,NaN
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,3.4,10.0,102,5500,24,30,13950,NaN,NaN,NaN
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,3.47,9.0,154,5000,19,26,16500,NaN,NaN,NaN
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,2.68,9.0,111,5000,21,27,16500,NaN,NaN,NaN
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,2.68,9.0,111,5000,21,27,13495,NaN,NaN,NaN

In [11]:
#Ejercicio10: ver los tipos de datos
df_replaced.dtypes

symboling              int64
normalized-losses     object
make                  object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base            object
length               float64
width                float64
height               float64
curb-weight          float64
engine-type            int64
num-of-cylinders      object
engine-size           object
fuel-system            int64
bore                  object
stroke                object
compression-ratio     object
horsepower           float64
horsepower-binned     object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
city-L/100km         float64
diesel               float64
gas                  float64
dtype: object

In [12]:
# Ejercicio11: Corregir el formato del precio
df_replaced['price'] = df_replaced['price'].astype('float')
df_replaced['horsepower'] = df_replaced['horsepower'].astype('int64')

In [14]:
# Ejercicio12: Verificar la correccion del formato del precio

In [13]:
#Ejercicio 08: Describir la columna Precio
df_replaced['price'].describe()

count      205.000000
mean     13207.129353
std       7868.768212
min       5118.000000
25%       7788.000000
50%      10595.000000
75%      16500.000000
max      45400.000000
Name: price, dtype: float64

In [15]:
#Ejercicio 09: Mostrar los elementos del dataFrame cuyos precios son mayores a 5000
df_replaced[df_replaced['price'] > 5000]

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,horsepower,horsepower-binned,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,diesel,gas
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,2.68,9,111,5000,21,27,13495.0,NaN,NaN,NaN
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,2.68,9,111,5000,21,27,16500.0,NaN,NaN,NaN
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,3.47,9,154,5000,19,26,16500.0,NaN,NaN,NaN
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,3.4,10,102,5500,24,30,13950.0,NaN,NaN,NaN
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,3.4,8,115,5500,18,22,17450.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,3.15,9,114,5400,23,28,16845.0,NaN,NaN,NaN
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,3.15,8,160,5300,19,25,19045.0,NaN,NaN,NaN
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,2.87,8,134,5500,18,23,21485.0,NaN,NaN,NaN
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,3.4,23,106,4800,26,27,22470.0,NaN,NaN,NaN
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,3.15,9,114,5400,19,25,22625.0,NaN,NaN,NaN

In [16]:
#Ejercicio 10: Mostrar los elementos del dataFrame cuyos precios son mayores a 5000 y son marca audi
df_replaced[(df_replaced.price > 5000) & (df_replaced.make == 'audi')]

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,horsepower,horsepower-binned,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,diesel,gas
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,3.4,10,102,5500,24,30,13950.000000,NaN,NaN,NaN
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,3.4,8,115,5500,18,22,17450.000000,NaN,NaN,NaN
5,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,3.4,8,110,5500,19,25,15250.000000,NaN,NaN,NaN
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,3.4,8,110,5500,19,25,17710.000000,NaN,NaN,NaN
7,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,3.4,8,110,5500,19,25,18920.000000,NaN,NaN,NaN
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,3.4,8,140,5500,17,20,23875.000000,NaN,NaN,NaN
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,3.4,7,160,5500,16,22,13207.129353,NaN,NaN,NaN

In [18]:
#Ejercicio 11: Establecer la influencia de tamaño del motor y la carroceria sobre el precio del auto

In [19]:
#Ejercicio 12: Graficar los resultados anteriores

In [20]:
#Ejercicio 13: Graficar la dispercion del tamaño del motor y el precio

In [21]:
#Ejercicio 14: Analizar la influencia de la ubicacion del motor en el precio

# Modelo Predictivo
### Regresión Lineal Simple

Obtencion de los coeficientes

In [22]:
# Los coeficientes

### El modelo calculado tendra la siguiente forma :

$$ Y_{HAT} =  B_0 + B_1*X $$